"""Initial migration

Revision ID: 49997aa3b349
Revises: 
Create Date: 2026-03-27 10:25:36.665193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49997aa3b349'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('erp_code', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=True)
    op.create_table('crm_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_state_id'), 'crm_state', ['id'], unique=False)
    op.create_table('oportunidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_projeto', sa.String(), nullable=True),
    sa.Column('empresa', sa.String(), nullable=True),
    sa.Column('contato_nome', sa.String(), nullable=True),
    sa.Column('contato_cargo', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('etapa', sa.String(), nullable=True),
    sa.Column('temperatura', sa.String(), nullable=True),
    sa.Column('integrador_nome', sa.String(), nullable=True),
    sa.Column('consumo_mensal', sa.Integer(), nullable=True),
    sa.Column('subsidio_haco', sa.Boolean(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oportunidades_id'), 'oportunidades', ['id'], unique=False)
    op.create_table('faturamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('pedido_haco', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faturamentos_id'), 'faturamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faturamentos_id'), table_name='faturamentos')
    op.drop_table('faturamentos')
    op.drop_index(op.f('ix_oportunidades_id'), table_name='oportunidades')
    op.drop_table('oportunidades')
    op.drop_index(op.f('ix_crm_state_id'), table_name='crm_state')
    op.drop_table('crm_state')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
